/**
 * ----------------------------------------
 * Module: Scaffolder Application Features
 * ----------------------------------------
 *
 * Installs optional application-owned examples for routing, localization,
 * testing, and styling after a starter has been copied.
 * ----------------------------------------
 */

import { mkdir, rename, readdir, writeFile } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import type { ScaffoldPlan } from "../types.ts";

/** Applies language conversion and optional feature files to one starter. */
export async function installApplicationFeatures(plan: ScaffoldPlan) {
  if (plan.language === "typescript") {
    await convertSourceToTypeScript(join(plan.destination, "src"));
  }

  await writeMainEntry(plan);
  await writeGlobalStyles(plan);

  if (plan.router) await writeRouterExample(plan);
  if (plan.i18n) await writeLocalizationExample(plan);
  if (plan.testing !== "none") await writeTests(plan);
}

async function writeMainEntry(plan: ScaffoldPlan) {
  const extension = sourceExtension(plan);
  await writeText(join(plan.destination, `src/main.${extension}`), `import { mountVeloDom } from "velodom/vite";
import "./style.css";

await mountVeloDom();
`);
}

async function writeGlobalStyles(plan: ScaffoldPlan) {
  const tailwind = plan.tailwind ? '@import "tailwindcss";\n\n' : "";
  await writeText(join(plan.destination, "src/style.css"), `${tailwind}:root {
  color: #172033;
  background: #f7f8fc;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
  font-synthesis: none;
}

* {
  box-sizing: border-box;
}
body {
  margin: 0;
  min-width: 320px;
}
a {
  color: inherit;
}
button,
input {
  font: inherit;
}
.shell {
  width: min(68rem, calc(100% - 2rem));
  margin-inline: auto;
}
.site-nav {
  display: flex;
  gap: 1rem;
  align-items: center;
  padding-block: 1.25rem;
}
.site-nav a {
  text-decoration: none;
}
.site-nav .brand {
  margin-inline-end: auto;
  font-weight: 800;
}
.hero {
  min-height: 70vh;
  display: grid;
  align-content: center;
  gap: 1rem;
}
.hero h1 {
  max-width: 14ch;
  margin: 0;
  font-size: clamp(2.6rem, 8vw, 6rem);
  line-height: 0.95;
}
.hero p {
  max-width: 42rem;
  font-size: 1.12rem;
  line-height: 1.75;
  color: #526078;
}
.button {
  width: fit-content;
  border: 0;
  border-radius: 0.8rem;
  padding: 0.8rem 1rem;
  color: white;
  background: #5445ee;
  cursor: pointer;
}
.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr));
  gap: 1rem;
}
.card {
  padding: 1.25rem;
  border: 1px solid #dce2ee;
  border-radius: 1rem;
  background: white;
}
[dir="rtl"] {
  text-align: start;
}
`);
}

async function writeRouterExample(plan: ScaffoldPlan) {
  const extension = sourceExtension(plan);
  await writeText(join(plan.destination, "src/pages/about/index.html"), `<main class="shell hero">
  <p>VeloDom route</p>
  <h1>About this project</h1>
  <p>This route was discovered from its folder. No route table was required.</p>
</main>
`);
  await writeText(join(plan.destination, `src/pages/about/config.${extension}`), `export default {
  path: "/about",
  seo: {
    title: "About",
    description: "A folder-discovered VeloDom route.",
  },
};
`);
  await writeHomeConfig(plan, true);
  await writeNavigation(plan);
}

async function writeHomeConfig(plan: ScaffoldPlan, withLayout: boolean) {
  const extension = sourceExtension(plan);
  await writeText(join(plan.destination, `src/pages/home/config.${extension}`), `export default {
  path: "/",
  ${withLayout ? 'layout: "default",\n  ' : ""}seo: {
    title: "${plan.starter === "blog" ? "VeloDom Blog" : "VeloDom Starter"}",
    description: "An editable ${plan.starter} application generated by VeloDom.",
  },
};
`);
}

async function writeNavigation(plan: ScaffoldPlan) {
  const links = [
    '<a href="/" vd-nav>Home</a>',
    ...(plan.starter === "blog" ? ['<a href="/posts" vd-nav>Posts</a>'] : []),
    '<a href="/about" vd-nav>About</a>',
    ...(plan.i18n ? ['<a href="/localization" vd-nav>Languages</a>'] : [])
  ];

  await writeText(join(plan.destination, "src/components/site-nav/index.html"), `<nav class="site-nav shell" aria-label="Primary navigation">
  <a class="brand" href="/" vd-nav>VeloDom</a>
  ${links.join("\n  ")}
</nav>
`);
  await writeText(join(plan.destination, "src/layouts/default/index.html"), `<vd-component name="site-nav"></vd-component>
<vd-page></vd-page>
`);
}

async function writeLocalizationExample(plan: ScaffoldPlan) {
  const extension = sourceExtension(plan);
  const type = plan.language === "typescript" ? ": \"en\" | \"ar\"" : "";
  await writeText(join(plan.destination, `src/i18n.${extension}`), `import { createLocalization, defineLocaleDictionary } from "velodom/localization";

/** Application-owned dictionaries consumed by VeloDom build integration. */
export const localizationOptions = {
  defaultLocale: "en",
  locales: {
    en: {
      lang: "en",
      messages: defineLocaleDictionary({ greeting: "Hello from VeloDom" }),
    },
    ar: {
      lang: "ar",
      messages: defineLocaleDictionary({ greeting: "مرحبًا من VeloDom" }),
    },
  },
}${plan.language === "typescript" ? " as const" : ""};

/** Typed localization controller shared by application pages and build hooks. */
export const i18n = createLocalization(localizationOptions);
/** Applies one explicit locale and writing direction to the current document. */
export function applyLocale(locale${type}) {
  document.documentElement.lang = locale;
  document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
}
`);
  await writeText(join(plan.destination, "src/pages/localization/index.html"), `<main class="shell hero">
  <p>Optional localization</p>
  <h1 vd-text="greeting"></h1>
  <div>
    <button class="button" type="button" vd-on:click="setLocale('en')">English</button>
    <button class="button" type="button" vd-on:click="setLocale('ar')">العربية</button>
  </div>
</main>
`);
  await writeText(join(plan.destination, `src/pages/localization/script.${extension}`), localizationScript(plan));
  await writeText(join(plan.destination, `src/pages/localization/config.${extension}`), `export default {
  path: "/localization",
  layout: "default",
  seo: {
    title: "Localization",
    description: "English and Arabic localization example.",
  },
};
`);

  if (plan.router) await writeNavigation(plan);
}

function localizationScript(plan: ScaffoldPlan) {
  const localeType = plan.language === "typescript" ? ': "en" | "ar"' : "";
  return `import { applyLocale, i18n } from "../../i18n.${sourceExtension(plan)}";

/** Shallow page state for the generated locale-switching example. */
export const state = {
  locale: "en"${plan.language === "typescript" ? ' as "en" | "ar"' : ""},
  greeting: i18n.t("en", "greeting"),
  setLocale(locale${localeType}) {
    this.locale = locale;
    this.greeting = i18n.t(locale, "greeting");
    applyLocale(locale);
  },
};
`;
}

async function writeTests(plan: ScaffoldPlan) {
  const extension = sourceExtension(plan);

  if (plan.testing === "unit" || plan.testing === "all") {
    // Keep unit tests executable on the minimum supported Node version without
    // requiring a TypeScript loader merely because application source is typed.
    await writeText(join(plan.destination, "tests/unit/project.test.js"), `import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("generated project depends on VeloDom", async () => {
  const manifest = JSON.parse(await readFile(new URL("../../package.json", import.meta.url), "utf8"));
  assert.match(manifest.dependencies.velodom, /^\\^\\d+\\./);
});
`);
  }

  if (plan.testing === "e2e" || plan.testing === "all") {
    await writeText(join(plan.destination, `tests/e2e/home.spec.${extension}`), `import { expect, test } from "@playwright/test";

test("renders the VeloDom starter", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("h1").first()).toBeVisible();
});
`);
  }
}

async function convertSourceToTypeScript(directory: string) {
  const entries = await readdir(directory, { withFileTypes: true });

  for (const entry of entries) {
    const path = join(directory, entry.name);

    if (entry.isDirectory()) {
      await convertSourceToTypeScript(path);
      continue;
    }

    if (extname(entry.name) === ".js") {
      await rename(path, path.slice(0, -3) + ".ts");
    }
  }
}

function sourceExtension(plan: ScaffoldPlan) {
  return plan.language === "typescript" ? "ts" : "js";
}

async function writeText(file: string, source: string) {
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, source);
}
