/**
 * ----------------------------------------
 * Module: Scaffolder Application Features
 * ----------------------------------------
 *
 * Installs optional application-owned examples for routing, localization,
 * testing, and styling after a starter has been copied.
 * ----------------------------------------
 */

import { mkdir, rename, readdir, writeFile } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import type { ScaffoldPlan } from "../types.ts";
import {
  createLocalizationFeatureFiles,
  createTestingFeatureFiles
} from "./optional-files.ts";

/** Applies language conversion and optional feature files to one starter. */
export async function installApplicationFeatures(plan: ScaffoldPlan) {
  if (plan.language === "typescript") {
    await convertSourceToTypeScript(join(plan.destination, "src"));
  }

  await writeMainEntry(plan);
  await writeGlobalStyles(plan);

  if (plan.router) await writeRouterExample(plan);
  if (plan.i18n) await writeLocalizationExample(plan);
  if (plan.testing !== "none") await writeTests(plan);
}

/** Writes the main entry. */
async function writeMainEntry(plan: ScaffoldPlan) {
  const extension = sourceExtension(plan);
  await writeText(join(plan.destination, `src/main.${extension}`), `import { mountVeloDom } from "velodom/vite";
import "./style.css";

await mountVeloDom();
`);
}

/** Writes the global styles. */
async function writeGlobalStyles(plan: ScaffoldPlan) {
  const tailwind = plan.tailwind ? '@import "tailwindcss";\n\n' : "";
  await writeText(join(plan.destination, "src/style.css"), `${tailwind}:root {
  color: #172033;
  background: #f7f8fc;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
  font-synthesis: none;
}

* {
  box-sizing: border-box;
}
body {
  margin: 0;
  min-width: 320px;
}
a {
  color: inherit;
}
button,
input {
  font: inherit;
}
.shell {
  width: min(68rem, calc(100% - 2rem));
  margin-inline: auto;
}
.site-nav {
  display: flex;
  gap: 1rem;
  align-items: center;
  padding-block: 1.25rem;
}
.site-nav a {
  text-decoration: none;
}
.site-nav .brand {
  margin-inline-end: auto;
  font-weight: 800;
}
.hero {
  min-height: 70vh;
  display: grid;
  align-content: center;
  gap: 1rem;
}
.hero h1 {
  max-width: 14ch;
  margin: 0;
  font-size: clamp(2.6rem, 8vw, 6rem);
  line-height: 0.95;
}
.hero p {
  max-width: 42rem;
  font-size: 1.12rem;
  line-height: 1.75;
  color: #526078;
}
.button {
  width: fit-content;
  border: 0;
  border-radius: 0.8rem;
  padding: 0.8rem 1rem;
  color: white;
  background: #5445ee;
  cursor: pointer;
}
.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr));
  gap: 1rem;
}
.card {
  padding: 1.25rem;
  border: 1px solid #dce2ee;
  border-radius: 1rem;
  background: white;
}
[dir="rtl"] {
  text-align: start;
}
`);
}

/** Writes the router example. */
async function writeRouterExample(plan: ScaffoldPlan) {
  const extension = sourceExtension(plan);
  await writeText(join(plan.destination, "src/pages/about/index.html"), `<main class="shell hero">
  <p>VeloDom route</p>
  <h1>About this project</h1>
  <p>This route was discovered from its folder. No route table was required.</p>
</main>
`);
  await writeText(join(plan.destination, `src/pages/about/config.${extension}`), `export default {
  path: "/about",
  seo: {
    title: "About",
    description: "A folder-discovered VeloDom route.",
  },
};
`);
  await writeHomeConfig(plan, true);
  await writeNavigation(plan);
}

/** Writes the home config. */
async function writeHomeConfig(plan: ScaffoldPlan, withLayout: boolean) {
  const extension = sourceExtension(plan);
  await writeText(join(plan.destination, `src/pages/home/config.${extension}`), `export default {
  path: "/",
  ${withLayout ? 'layout: "default",\n  ' : ""}seo: {
    title: "${plan.starter === "blog" ? "VeloDom Blog" : "VeloDom Starter"}",
    description: "An editable ${plan.starter} application generated by VeloDom.",
  },
};
`);
}

/** Writes the navigation. */
async function writeNavigation(plan: ScaffoldPlan) {
  const links = [
    '<a href="/" vd-nav>Home</a>',
    ...(plan.starter === "blog" ? ['<a href="/posts" vd-nav>Posts</a>'] : []),
    '<a href="/about" vd-nav>About</a>',
    ...(plan.i18n ? ['<a href="/localization" vd-nav>Languages</a>'] : [])
  ];

  await writeText(join(plan.destination, "src/components/site-nav/index.html"), `<nav class="site-nav shell" aria-label="Primary navigation">
  <a class="brand" href="/" vd-nav>VeloDom</a>
  ${links.join("\n  ")}
</nav>
`);
  await writeText(join(plan.destination, "src/layouts/default/index.html"), `<vd-component name="site-nav"></vd-component>
<vd-page></vd-page>
`);
}

/** Writes the localization example. */
async function writeLocalizationExample(plan: ScaffoldPlan) {
  await writeGeneratedFiles(
    plan.destination,
    createLocalizationFeatureFiles(plan.language)
  );

  if (plan.router) await writeNavigation(plan);
}

/** Writes the tests. */
async function writeTests(plan: ScaffoldPlan) {
  if (plan.testing === "none") return;

  await writeGeneratedFiles(
    plan.destination,
    createTestingFeatureFiles(
      plan.language,
      plan.testing,
      plan.packageManager === "pnpm" || plan.packageManager === "yarn"
        ? `${plan.packageManager} dev`
        : `${plan.packageManager} run dev`
    )
  );
}

/** Writes a deterministic map of generated application files. */
async function writeGeneratedFiles(
  destination: string,
  files: Record<string, string>
) {
  await Promise.all(Object.entries(files).map(([file, source]) => (
    writeText(join(destination, file), source)
  )));
}

/** Converts the source to type script. */
async function convertSourceToTypeScript(directory: string) {
  const entries = await readdir(directory, { withFileTypes: true });

  for (const entry of entries) {
    const path = join(directory, entry.name);

    if (entry.isDirectory()) {
      await convertSourceToTypeScript(path);
      continue;
    }

    if (extname(entry.name) === ".js") {
      await rename(path, path.slice(0, -3) + ".ts");
    }
  }
}

/** Performs the internal `sourceExtension()` operation. */
function sourceExtension(plan: ScaffoldPlan) {
  return plan.language === "typescript" ? "ts" : "js";
}

/** Writes the text. */
async function writeText(file: string, source: string) {
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, source);
}
