/**
 * ----------------------------------------
 * Module: Build-Time Asset Helpers
 * ----------------------------------------
 *
 * Inspects local image files and creates standard responsive-image attributes
 * from explicit application-owned variants. This Node-only module keeps image
 * quality tooling out of the VeloDom browser runtime and never transforms an
 * image without the application's chosen image pipeline.
 * ----------------------------------------
 */

import {
  readFile,
  readdir
} from "node:fs/promises";
import {
  extname,
  join
} from "node:path";

/** Supported local image formats that the inspector can recognize. */
export type ImageFormat = "gif" | "jpeg" | "png" | "svg" | "webp" | "unknown";

/** Static image information read from a local source file. */
export interface AssetImageInspection {
  bytes: number;
  format: ImageFormat;
  height?: number;
  path: string;
  width?: number;
}

/** Options for inspecting images beneath an application-owned directory. */
export interface AssetImageDirectoryOptions {
  /** Root directory to inspect, normally `src/assets`. */
  root: string;
  /** Optional byte threshold used to report large files. */
  maxBytes?: number;
}

/** Aggregate image-inspection result for local build scripts or CI. */
export interface AssetImageDirectoryReport {
  images: AssetImageInspection[];
  oversized: AssetImageInspection[];
}

/** One explicit responsive variant emitted by an application's image pipeline. */
export interface ResponsiveImageVariant {
  /** Public URL for the already-generated variant. */
  src: string;
  /** Intrinsic pixel width for this variant. */
  width: number;
}

/** Input used to build standards-based image attributes. */
export interface ResponsiveImageOptions {
  /** Fallback image URL. */
  src: string;
  /** Intrinsic width of the fallback image, when known. */
  width?: number;
  /** Intrinsic height of the fallback image, when known. */
  height?: number;
  /** Explicit application-generated variants used for `srcset`. */
  variants?: ResponsiveImageVariant[];
  /** Standard HTML `sizes` value for responsive variants. */
  sizes?: string;
  /** Native loading hint. Defaults to `lazy`. */
  loading?: "eager" | "lazy";
  /** Native decoding hint. Defaults to `async`. */
  decoding?: "async" | "auto" | "sync";
}

/** Standard `<img>` attributes generated without adding a runtime directive. */
export interface ResponsiveImageAttributes {
  decoding: "async" | "auto" | "sync";
  height?: string;
  loading: "eager" | "lazy";
  sizes?: string;
  src: string;
  srcset?: string;
  width?: string;
}

const IMAGE_EXTENSIONS = new Set([
  ".gif",
  ".jpeg",
  ".jpg",
  ".png",
  ".svg",
  ".webp"
]);

/**
 * Reads a local image's byte size and intrinsic dimensions when its format is
 * supported. Unknown formats are returned without fabricated dimensions.
 */
export async function inspectImageAsset(path: string): Promise<AssetImageInspection> {
  const source = await readFile(path);
  const format = detectImageFormat(source, extname(path));
  const dimensions = readImageDimensions(source, format);

  return {
    bytes: source.byteLength,
    format,
    path,
    ...dimensions
  };
}

/**
 * Inspects every supported image below one application-owned directory. The
 * result is suitable for a build script or CI report, not browser code.
 */
export async function inspectImageDirectory(
  options: AssetImageDirectoryOptions
): Promise<AssetImageDirectoryReport> {
  const files = await discoverImageFiles(options.root);
  const images = await Promise.all(files.map(inspectImageAsset));
  const maxBytes = options.maxBytes;

  return {
    images,
    oversized: typeof maxBytes === "number"
      ? images.filter(image => image.bytes > maxBytes)
      : []
  };
}

/**
 * Creates normal HTML image attributes from variants generated by the
 * application or a chosen asset pipeline. It never creates or resizes files.
 */
export function createResponsiveImageAttributes(
  options: ResponsiveImageOptions
): ResponsiveImageAttributes {
  const src = requireNonEmptyString(options.src, "src");
  const width = normalizeDimension(options.width, "width");
  const height = normalizeDimension(options.height, "height");
  const variants = normalizeVariants(options.variants || []);
  const sizes = options.sizes?.trim();

  if (variants.length && !sizes) {
    throw new Error("Responsive image variants require a non-empty sizes value.");
  }

  return {
    src,
    ...(width ? { width: String(width) } : {}),
    ...(height ? { height: String(height) } : {}),
    ...(variants.length ? {
      srcset: variants.map(variant => `${variant.src} ${variant.width}w`).join(", "),
      sizes
    } : {}),
    loading: options.loading || "lazy",
    decoding: options.decoding || "async"
  };
}

async function discoverImageFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, {
    withFileTypes: true
  });
  const nested = await Promise.all(entries.map(async entry => {
    const path = join(root, entry.name);

    if (entry.isDirectory()) return discoverImageFiles(path);
    if (entry.isFile() && IMAGE_EXTENSIONS.has(extname(entry.name).toLowerCase())) {
      return [path];
    }

    return [];
  }));

  return nested.flat().sort((left, right) => left.localeCompare(right));
}

function detectImageFormat(source: Uint8Array, extension: string): ImageFormat {
  if (source.subarray(0, 8).every((value, index) => value === [137, 80, 78, 71, 13, 10, 26, 10][index])) {
    return "png";
  }
  if (source[0] === 0xff && source[1] === 0xd8) return "jpeg";
  if (new TextDecoder().decode(source.subarray(0, 6)) === "GIF87a" || new TextDecoder().decode(source.subarray(0, 6)) === "GIF89a") {
    return "gif";
  }
  if (new TextDecoder().decode(source.subarray(0, 4)) === "RIFF" && new TextDecoder().decode(source.subarray(8, 12)) === "WEBP") {
    return "webp";
  }
  if (extension.toLowerCase() === ".svg") return "svg";
  return "unknown";
}

function readImageDimensions(source: Uint8Array, format: ImageFormat) {
  switch (format) {
    case "png":
      return source.byteLength >= 24
        ? { width: readUInt32Be(source, 16), height: readUInt32Be(source, 20) }
        : {};
    case "gif":
      return source.byteLength >= 10
        ? { width: readUInt16Le(source, 6), height: readUInt16Le(source, 8) }
        : {};
    case "jpeg":
      return readJpegDimensions(source);
    case "webp":
      return readWebpDimensions(source);
    case "svg":
      return readSvgDimensions(new TextDecoder().decode(source));
    default:
      return {};
  }
}

function readJpegDimensions(source: Uint8Array) {
  let offset = 2;

  while (offset + 9 < source.byteLength) {
    if (source[offset] !== 0xff) {
      offset += 1;
      continue;
    }

    const marker = source[offset + 1];
    const length = readUInt16Be(source, offset + 2);
    const isStartOfFrame = marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker);

    if (isStartOfFrame && offset + 8 < source.byteLength) {
      return {
        height: readUInt16Be(source, offset + 5),
        width: readUInt16Be(source, offset + 7)
      };
    }

    if (length < 2) return {};
    offset += length + 2;
  }

  return {};
}

function readWebpDimensions(source: Uint8Array) {
  const chunk = new TextDecoder().decode(source.subarray(12, 16));

  if (chunk === "VP8X" && source.byteLength >= 30) {
    return {
      width: readUInt24Le(source, 24) + 1,
      height: readUInt24Le(source, 27) + 1
    };
  }

  if (chunk === "VP8 " && source.byteLength >= 30) {
    return {
      width: readUInt16Le(source, 26) & 0x3fff,
      height: readUInt16Le(source, 28) & 0x3fff
    };
  }

  if (chunk === "VP8L" && source.byteLength >= 25) {
    const bits = source[21] | (source[22] << 8) | (source[23] << 16) | (source[24] << 24);
    return {
      width: (bits & 0x3fff) + 1,
      height: ((bits >> 14) & 0x3fff) + 1
    };
  }

  return {};
}

function readSvgDimensions(source: string) {
  const viewBox = source.match(/\bviewBox\s*=\s*["']\s*[-+\d.eE]+\s+[-+\d.eE]+\s+([-+\d.eE]+)\s+([-+\d.eE]+)\s*["']/i);
  const width = readSvgLength(source, "width");
  const height = readSvgLength(source, "height");

  return {
    ...(width ? { width } : viewBox ? { width: Number(viewBox[1]) } : {}),
    ...(height ? { height } : viewBox ? { height: Number(viewBox[2]) } : {})
  };
}

function readSvgLength(source: string, name: string) {
  const value = source.match(new RegExp(`\\b${name}\\s*=\\s*["']([0-9]+(?:\\.[0-9]+)?)(?:px)?["']`, "i"));
  return value ? Number(value[1]) : undefined;
}

function normalizeVariants(variants: ResponsiveImageVariant[]) {
  const seenWidths = new Set<number>();

  return variants.map(variant => {
    const src = requireNonEmptyString(variant.src, "variant src");
    const width = normalizeDimension(variant.width, "variant width");

    if (!width || seenWidths.has(width)) {
      throw new Error("Responsive image variant widths must be unique positive numbers.");
    }

    seenWidths.add(width);
    return { src, width };
  }).sort((left, right) => left.width - right.width);
}

function requireNonEmptyString(value: string, label: string) {
  const normalized = value.trim();

  if (!normalized) throw new Error(`Responsive image ${label} must be a non-empty string.`);
  return normalized;
}

function normalizeDimension(value: number | undefined, label: string) {
  if (value === undefined) return undefined;
  if (!Number.isFinite(value) || value <= 0 || !Number.isInteger(value)) {
    throw new Error(`Responsive image ${label} must be a positive integer.`);
  }
  return value;
}

function readUInt16Be(source: Uint8Array, offset: number) {
  return (source[offset] << 8) | source[offset + 1];
}

function readUInt16Le(source: Uint8Array, offset: number) {
  return source[offset] | (source[offset + 1] << 8);
}

function readUInt24Le(source: Uint8Array, offset: number) {
  return source[offset] | (source[offset + 1] << 8) | (source[offset + 2] << 16);
}

function readUInt32Be(source: Uint8Array, offset: number) {
  return ((source[offset] * 0x1000000) + (source[offset + 1] << 16) + (source[offset + 2] << 8) + source[offset + 3]) >>> 0;
}
